events { worker_connections 1024; }

http {
    upstream auth        { server auth_service:8001; }
    upstream incident    { server incident_service:8002; }
    upstream dispatch    { server dispatch_service:8003; }
    upstream analytics   { server analytics_service:8004; }

    server {
        listen 80;

        location /auth/       { proxy_pass http://auth/; }
        
        location /incidents/  { proxy_pass http://incident/; }
        location /vehicles/   { proxy_pass http://dispatch/; }
        location /analytics/  { proxy_pass http://analytics/; }

        # WebSocket passthrough
        location /ws/ {
            proxy_pass http://dispatch;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}